language: bash
branches:
  only:
    - master
addons:
  ssh_known_hosts: ${SFTP_HOST}
script:
  - echo "Running deployment"
  - pwd
  - ls
after_success:
  - echo "Checking master branch..."
  - if [[ "$TRAVIS_BRANCH" != "master" ]]; then echo "We're not on the master branch."; exit 0; fi
  - echo "Starting publish on ${SFTP_HOST}"
  - echo "${SFTP_PRIVATEKEY}" >/tmp/sftp_rsa
  - sed -i 's/NEWLINE/\n/g' /tmp/sftp_rsa
  - chmod 400 /tmp/sftp_rsa
  - echo "Uploading..."
  - scp -o "StrictHostKeyChecking no" -i /tmp/sftp_rsa index.html ${SFTP_USERNAME}@${SFTP_HOST}:/var/www/tomstein.me/index.html
  - scp -o "StrictHostKeyChecking no" -i /tmp/sftp_rsa datenschutz.html ${SFTP_USERNAME}@${SFTP_HOST}:/var/www/tomstein.me/datenschutz.html
  - ssh -o "StrictHostKeyChecking no" -i /tmp/sftp_rsa scholli@${SFTP_HOST} "rm -rf /var/www/tomstein.me/css"
  - scp -o "StrictHostKeyChecking no" -i /tmp/sftp_rsa -r css ${SFTP_USERNAME}@${SFTP_HOST}:/var/www/tomstein.me/css
  - ssh -o "StrictHostKeyChecking no" -i /tmp/sftp_rsa scholli@${SFTP_HOST} "rm -rf /var/www/tomstein.me/images"
  - scp -o "StrictHostKeyChecking no" -i /tmp/sftp_rsa -r images ${SFTP_USERNAME}@${SFTP_HOST}:/var/www/tomstein.me/images
  - ssh -o "StrictHostKeyChecking no" -i /tmp/sftp_rsa scholli@${SFTP_HOST} "rm -rf /var/www/tomstein.me/js"
  - scp -o "StrictHostKeyChecking no" -i /tmp/sftp_rsa -r js ${SFTP_USERNAME}@${SFTP_HOST}:/var/www/tomstein.me/js
  - ssh -o "StrictHostKeyChecking no" -i /tmp/sftp_rsa scholli@${SFTP_HOST} "rm -rf /var/www/tomstein.me/libs"
  - scp -o "StrictHostKeyChecking no" -i /tmp/sftp_rsa -r libs ${SFTP_USERNAME}@${SFTP_HOST}:/var/www/tomstein.me/libs
  - yes | rm /tmp/sftp_rsa
  