name: Site Reliability
on: 
  push:
    branches: 
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 4 * * *'
jobs:
  crawl_for_broken_links:
    runs-on: ubuntu-latest
    name: Broken-Links-Crawler
    steps:
    - name: Debug Action
      uses: hmarr/debug-action@v1.0.0
    - name: Checking links
      id: checking
      uses: ScholliYT/Broken-Links-Crawler-Action@v3
      with:
        website_url: 'https://tomstein.me'
        exclude_url_prefix: 'mailto:,https://www.linkedin.com,https://linkedin.com'
        verbose: 'true'
        max_retry_time: 30
        max_retries: 5
    # Use the output from the `checking` step
    - name: Telegram Message Notify on Error
      uses: appleboy/telegram-action@0.0.5
      if: failure()
      id: notify_on_error_telegram
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
      with:
        args: Found broken links on https://tomstein.me/!
